### ISSUE TITLE
deployment of cloud foundry app failed in Bluemix 

### ISSUE THREAD

**Issue by evalyan** [IBM/increase-retail-revenues-leveraging-hybrid-cloud-on-mainframes#1]
![image](https://user-images.githubusercontent.com/11161714/28888865-2a5e16b6-7790-11e7-8bc4-6947943d4143.png)

But I can use bluemix data centers in other regions, actually there're 4 data center available for my bluemix account.  When I tried the journey yesterday, the Node.js App was deployed in Syndey data center (I can't remember if it's default for China users).  Today I tried to deploy the same App to US-South data center, and the failed step is fixed.  So that problem must be related to Sydney data center only.

**Comment by szihai** [comment]
Can you please provide more logs? There is not enough info.
One thing you can try is to use cf command directly and see if it works. the bx cf wrapper uses a different cf version which might cause trouble sometimes.

**Comment by evalyan** [comment]
Tester has successfully used the work around (US-South) to complete this step.  No logs are currently available.

**Comment by evalyan** [comment]
problem resolved
